import{a as v,S as w,i}from"./assets/vendor-CrlV4O_2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();const S="https://pixabay.com/api/",P="50282223-5a409711ad86c04843247122a",q=15;async function m(t,o){return console.log(o),(await v.get(S,{params:{key:P,q:t,page:o,per_page:q,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}const p=document.querySelector(".gallery"),u=document.querySelector(".loader"),a=document.querySelector(".js-load"),$=new w(".gallery a",{captionsData:"alt",captionDelay:250});function f(t){const o=t.map(({webformatURL:c,largeImageURL:l,tags:e,likes:r,views:s,comments:L,downloads:b})=>`<li class="gallery-item">
            <a href="${l}">
              <img src="${c}" alt="${e}" />
            </a>
            <div class="info">
              <p><b>Likes:</b> ${r}</p>
              <p><b>Views:</b> ${s}</p>
              <p><b>Comments:</b> ${L}</p>
              <p><b>Downloads:</b> ${b}</p>
            </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",o),$.refresh()}function B(){p.innerHTML=""}function g(){u.classList.add("is-active"),u.classList.remove("is-hidden")}function h(){u.classList.add("is-hidden"),u.classList.remove("is-active")}function M(){a.classList.add("is-active"),a.classList.remove("is-hidden")}function y(){a.classList.add("is-hidden"),a.classList.remove("is-active")}const O=document.querySelector(".form");let n=1,d="",x=5;a.addEventListener("click",C);function C(){n+=1,g(),m(d,n).then(t=>{f(t),n>=x&&(y(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}).catch(t=>{console.error(t),i.error({message:"Something went wrong. Please try again later.",position:"topCenter"})}).finally(()=>{h();const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}})}O.addEventListener("submit",E);function E(t){if(t.preventDefault(),console.log("Форма відправлена"),y(),d=t.target.elements["search-text"].value.trim(),d===""){i.warning({message:"Please enter a search term!",position:"topRight"});return}n=1,B(),g(),m(d,n).then(o=>{if(o.length===0){i.error({message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"});return}f(o)}).catch(o=>{console.error(o),i.error({message:"Something went wrong. Please try again later.",position:"topCenter"})}).finally(()=>{h(),M()}),t.target.reset()}
//# sourceMappingURL=index.js.map
