import{a as S,S as P,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const q="https://pixabay.com/api/",H="50282223-5a409711ad86c04843247122a",p=15;async function g(o,t){console.log(t);const s=await S.get(q,{params:{key:H,q:o,page:t,per_page:p,image_type:"photo",orientation:"horizontal",safesearch:!0}});return{hits:s.data.hits,totalHits:s.data.totalHits}}const h=document.querySelector(".gallery"),u=document.querySelector(".loader"),l=document.querySelector(".js-load"),$=new P(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:n,comments:v,downloads:w})=>`<li class="gallery-item">
            <a href="${i}">
              <img src="${s}" alt="${e}" />
            </a>
            <div class="info">
              <p><b>Likes:</b> ${r}</p>
              <p><b>Views:</b> ${n}</p>
              <p><b>Comments:</b> ${v}</p>
              <p><b>Downloads:</b> ${w}</p>
            </div>
        </li>`).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()}function B(){h.innerHTML=""}function L(){u.classList.add("is-active"),u.classList.remove("is-hidden")}function b(){u.classList.add("is-hidden"),u.classList.remove("is-active")}function E(){l.classList.add("is-active"),l.classList.remove("is-hidden")}function m(){l.classList.add("is-hidden"),l.classList.remove("is-active")}const M=document.querySelector(".form");let a=1,d="",f=0;l.addEventListener("click",O);async function O(){a+=1,L();try{const{hits:o}=await g(d,a);y(o),a*p>=f&&(m(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){console.error(o),c.error({message:"Something went wrong. Please try again later.",position:"topCenter"})}finally{b();const o=document.querySelector(".gallery-item");if(o){const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}}M.addEventListener("submit",x);async function x(o){if(o.preventDefault(),m(),d=o.target.elements.searchText.value.trim(),d===""){c.warning({message:"Please enter a search term!",position:"topRight"});return}a=1,B(),L();try{const{hits:t,totalHits:s}=await g(d,a);if(f=s,s===0||t.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t),a*p<f?E():m()}catch(t){console.error(t),c.error({message:"Something went wrong. Please try again later.",position:"topCenter"})}finally{b()}o.target.reset()}
//# sourceMappingURL=index.js.map
